-- Opcode Definitions for Custom VM
local Opcode = {
    LOADK = 0,
    LOADBOOL = 1,
    LOADNIL = 2,
    ADD = 3,
    SUB = 4,
    MUL = 5,
    DIV = 6,
    MOD = 7,
    POW = 8,
    UNM = 9,
    NOT = 10,
    LEN = 11,
    EQ = 12,
    LT = 13,
    LE = 14,
    NEWTABLE = 15,
    GETTABLE = 16,
    SETTABLE = 17,
    GETGLOBAL = 18,
    SETGLOBAL = 19,
    CALL = 20,
    RETURN = 21,
    CLOSURE = 22,
    JMP = 23,
    FORPREP = 24,
    FORLOOP = 25,
    TEST = 26,
    MOVE = 27,
    GETUPVAL = 28,
    SETUPVAL = 29,
    CONCAT = 30,
    VARARG = 31,
}

local OpcodeInfo = {
    [Opcode.LOADK] = {name = "LOADK", args = 2},
    [Opcode.LOADBOOL] = {name = "LOADBOOL", args = 3},
    [Opcode.LOADNIL] = {name = "LOADNIL", args = 2},
    [Opcode.ADD] = {name = "ADD", args = 3},
    [Opcode.SUB] = {name = "SUB", args = 3},
    [Opcode.MUL] = {name = "MUL", args = 3},
    [Opcode.DIV] = {name = "DIV", args = 3},
    [Opcode.MOD] = {name = "MOD", args = 3},
    [Opcode.POW] = {name = "POW", args = 3},
    [Opcode.UNM] = {name = "UNM", args = 2},
    [Opcode.NOT] = {name = "NOT", args = 2},
    [Opcode.LEN] = {name = "LEN", args = 2},
    [Opcode.EQ] = {name = "EQ", args = 3},
    [Opcode.LT] = {name = "LT", args = 3},
    [Opcode.LE] = {name = "LE", args = 3},
    [Opcode.NEWTABLE] = {name = "NEWTABLE", args = 3},
    [Opcode.GETTABLE] = {name = "GETTABLE", args = 3},
    [Opcode.SETTABLE] = {name = "SETTABLE", args = 3},
    [Opcode.GETGLOBAL] = {name = "GETGLOBAL", args = 2},
    [Opcode.SETGLOBAL] = {name = "SETGLOBAL", args = 2},
    [Opcode.CALL] = {name = "CALL", args = 3},
    [Opcode.RETURN] = {name = "RETURN", args = 2},
    [Opcode.CLOSURE] = {name = "CLOSURE", args = 2},
    [Opcode.JMP] = {name = "JMP", args = 1},
    [Opcode.FORPREP] = {name = "FORPREP", args = 2},
    [Opcode.FORLOOP] = {name = "FORLOOP", args = 2},
    [Opcode.TEST] = {name = "TEST", args = 2},
    [Opcode.MOVE] = {name = "MOVE", args = 2},
    [Opcode.GETUPVAL] = {name = "GETUPVAL", args = 2},
    [Opcode.SETUPVAL] = {name = "SETUPVAL", args = 2},
    [Opcode.CONCAT] = {name = "CONCAT", args = 3},
    [Opcode.VARARG] = {name = "VARARG", args = 2},
}

return {
    Opcode = Opcode,
    OpcodeInfo = OpcodeInfo,
}