-- prometheus/vm/generator.lua
-- VM Runtime Generator - Creates secure VM runtime with embedded bytecode

local VMGenerator = {}
VMGenerator.__index = VMGenerator

function VMGenerator.new(config)
    local self = setmetatable({}, VMGenerator)
    self.config = config or {}
    return self
end

function VMGenerator:generateFromAST(ast, sourceCode)
    -- Compile AST to bytecode using VMCompiler
    local VMCompiler = require("prometheus.vm.Compiler")
    local compiler = VMCompiler:new()
    
    -- Compile AST to bytecode
    local bytecode = compiler:compile(ast)
    
    -- Generate VM runtime with the bytecode
    return self:generate(bytecode, self.config)
end

function VMGenerator:generate(bytecode, config)
    config = config or self.config
    
    -- Security settings
    local obfuscateVM = config.obfuscateVMRuntime ~= false
    local compressBytecode = config.compressBytecode ~= false
    local encryptBytecode = config.encryptBytecode ~= false
    local shuffleOpcodes = config.shuffleOpcodes ~= false
    local antiDebug = config.antiDebug ~= false
    
    -- Apply opcode shuffling if enabled
    local opcodeMapping = nil
    if shuffleOpcodes then
        bytecode, opcodeMapping = self:shuffleOpcodes(bytecode)
    end
    
    -- Encrypt bytecode if enabled
    local encryptionKey = nil
    if encryptBytecode then
        encryptionKey = math.random(0x1000, 0xFFFF)
        bytecode = self:encryptBytecode(bytecode, encryptionKey)
    end
    
    -- Generate VM runtime
    local vmRuntime = self:generateVMRuntime(obfuscateVM, encryptionKey, antiDebug)
    
    -- Serialize bytecode
    local serialized = self:serializeBytecode(bytecode, compressBytecode)
    
    -- Combine into final output
    local output = string.format([[
-- ================================================================
-- VM-Protected Lua Script
-- Generated by Prometheus VM Obfuscator
-- WARNING: Unauthorized modification will cause execution failure
-- ================================================================

%s

-- Execute bytecode
local __BYTECODE__ = %s
return __VM_EXECUTE__(__BYTECODE__)
]], vmRuntime, serialized)
    
    -- Apply final obfuscation to entire output if enabled
    if obfuscateVM then
        output = self:finalObfuscation(output)
    end
    
    return output
end

-- === Opcode Shuffling ===

function VMGenerator:shuffleOpcodes(bytecode)
    local opcodes = bytecode.opcodes
    local mapping = {}
    local shuffled = {}
    
    -- Create list of opcodes
    local opcodeList = {}
    for name, value in pairs(opcodes) do
        table.insert(opcodeList, {name = name, value = value})
    end
    
    -- Shuffle opcodes
    for i = #opcodeList, 2, -1 do
        local j = math.random(1, i)
        opcodeList[i], opcodeList[j] = opcodeList[j], opcodeList[i]
    end
    
    -- Create mapping
    for newValue, entry in ipairs(opcodeList) do
        mapping[entry.value] = newValue - 1
        shuffled[entry.name] = newValue - 1
    end
    
    -- Remap instructions
    for _, instr in ipairs(bytecode.instructions) do
        instr.opcode = mapping[instr.opcode] or instr.opcode
    end
    
    bytecode.opcodes = shuffled
    
    return bytecode, mapping
end

-- === Bytecode Encryption ===

function VMGenerator:encryptBytecode(bytecode, key)
    -- Encrypt instruction opcodes and operands
    for _, instr in ipairs(bytecode.instructions) do
        instr.opcode = self:xorEncrypt(instr.opcode, key)
        instr.operand = self:xorEncrypt(instr.operand, key)
    end
    
    -- Encrypt constants
    for i, const in ipairs(bytecode.constants) do
        if type(const) == "number" then
            bytecode.constants[i] = const + key
        end
    end
    
    bytecode.encrypted = true
    bytecode.key = key
    
    return bytecode
end

function VMGenerator:xorEncrypt(value, key)
    return bit32 and bit32.bxor(value, key) or value
end

-- === Bytecode Serialization ===

function VMGenerator:serializeBytecode(bytecode, compress)
    local parts = {}
    
    -- Serialize instructions
    local instructions = {}
    for _, instr in ipairs(bytecode.instructions) do
        table.insert(instructions, string.format("{%d,%d,%d}", 
            instr.opcode, instr.operand, instr.aux or 0))
    end
    
    -- Serialize constants
    local constants = {}
    for _, const in ipairs(bytecode.constants) do
        if type(const) == "string" then
            table.insert(constants, string.format("%q", const))
        elseif type(const) == "number" then
            table.insert(constants, tostring(const))
        elseif type(const) == "boolean" then
            table.insert(constants, tostring(const))
        else
            table.insert(constants, "nil")
        end
    end
    
    local result = string.format([[{
i={%s},
c={%s},
e=%s,
k=%s,
v="%s"
}]], 
        table.concat(instructions, ","),
        table.concat(constants, ","),
        bytecode.encrypted and "true" or "false",
        bytecode.key or "nil",
        bytecode.version or "1.0.0"
    )
    
    if compress then
        result = self:compressString(result)
    end
    
    return result
end

function VMGenerator:compressString(str)
    -- Base64 encode for compression
    local encoded = self:base64Encode(str)
    return string.format('__VM_DECODE__(%q)', encoded)
end

function VMGenerator:base64Encode(data)
    local b64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    return ((data:gsub('.', function(x) 
        local r,b='',x:byte()
        for i=8,1,-1 do r=r..(b%2^i-b%2^i/2>0 and '1' or '0') end
        return r;
    end)..'0000'):gsub('%d%d%d?%d?%d?%d?', function(x)
        if (#x < 6) then return '' end
        local c=0
        for i=1,6 do c=c+(x:sub(i,i)=='1' and 2^(6-i) or 0) end
        return b64chars:sub(c+1,c+1)
    end)..({ '', '==', '=' })[#data%3+1])
end

-- === VM Runtime Generation ===

function VMGenerator:generateVMRuntime(obfuscate, encryptionKey, antiDebug)
    -- Generate variable names
    local names = obfuscate and self:generateObfuscatedNames() or self:generateNormalNames()
    
    local vmCode = string.format([[
-- VM Runtime
local %s = {}  -- Stack
local %s = 0   -- Stack pointer
local %s = {}  -- Locals
local %s = _G  -- Globals

-- Base64 decoder
local function __VM_DECODE__(encoded)
    local b64chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
    local decoded = {}
    encoded = encoded:gsub('[^'..b64chars..'=]', '')
    encoded:gsub('.', function(c)
        if c ~= '=' then
            local b = b64chars:find(c) - 1
            table.insert(decoded, b)
        end
    end)
    local result = ''
    for i = 1, #decoded, 4 do
        local a, b, c, d = decoded[i], decoded[i+1], decoded[i+2], decoded[i+3]
        if a and b then
            result = result .. string.char(a * 4 + math.floor((b or 0) / 16))
            if c then
                result = result .. string.char(((b or 0) %% 16) * 16 + math.floor((c or 0) / 4))
                if d then
                    result = result .. string.char(((c or 0) %% 4) * 64 + (d or 0))
                end
            end
        end
    end
    return loadstring("return " .. result)()
end

-- Stack operations
local function %s(v)  -- push
    %s = %s + 1
    %s[%s] = v
end

local function %s()  -- pop
    local v = %s[%s]
    %s[%s] = nil
    %s = %s - 1
    return v
end

local function %s()  -- peek
    return %s[%s]
end

local function %s()  -- dup
    %s(%s())
end
]], 
        names.stack, names.sp, names.locals, names.globals,
        names.push, names.sp, names.sp, names.stack, names.sp,
        names.pop, names.stack, names.sp, names.stack, names.sp, names.sp, names.sp,
        names.peek, names.stack, names.sp,
        names.dup, names.push, names.peek
    )
    
    -- Add anti-debugging if enabled
    if antiDebug then
        vmCode = vmCode .. self:generateAntiDebug(names)
    end
    
    -- Add main executor
    vmCode = vmCode .. string.format([[

-- Main VM executor
function __VM_EXECUTE__(%s)
    local %s = %s.i      -- Instructions
    local %s = %s.c      -- Constants
    local %s = %s.e      -- Encrypted flag
    local %s = %s.k or 0 -- Encryption key
    
    local %s = 1  -- Program counter
    local %s = false  -- Halted flag
]], 
        names.bytecode,
        names.instructions, names.bytecode,
        names.constants, names.bytecode,
        names.encrypted, names.bytecode,
        names.key, names.bytecode,
        names.pc, names.halted
    )
    
    -- Add decryption if needed
    if encryptionKey then
        vmCode = vmCode .. string.format([[
    
    -- Decrypt bytecode if encrypted
    if %s then
        for _, %s in ipairs(%s) do
            %s[1] = bit32 and bit32.bxor(%s[1], %s) or %s[1]
            %s[2] = bit32 and bit32.bxor(%s[2], %s) or %s[2]
        end
        for %s, %s in ipairs(%s) do
            if type(%s) == "number" then
                %s[%s] = %s - %s
            end
        end
    end
]], 
            names.encrypted,
            names.instr, names.instructions,
            names.instr, names.instr, names.key, names.instr,
            names.instr, names.instr, names.key, names.instr,
            names.i, names.const, names.constants,
            names.const,
            names.constants, names.i, names.const, names.key
        )
    end
    
    -- Main execution loop
    vmCode = vmCode .. string.format([[
    
    -- Execution loop
    while not %s and %s <= #%s do
        local %s = %s[%s]
        local %s = %s[1]
        local %s = %s[2]
        
        -- Opcode dispatch
]], 
        names.halted, names.pc, names.instructions,
        names.instr, names.instructions, names.pc,
        names.opcode, names.instr,
        names.operand, names.instr
    )
    
    -- Generate opcode handlers
    vmCode = vmCode .. self:generateOpcodeHandlers(names, obfuscate)
    
    -- Close execution loop
    vmCode = vmCode .. string.format([[
        
        %s = %s + 1
    end
    
    -- Return result if available
    if %s > 0 then
        return %s()
    end
end
]], names.pc, names.pc, names.sp, names.pop)
    
    return vmCode
end

-- === Opcode Handlers ===

function VMGenerator:generateOpcodeHandlers(names, obfuscate)
    local handlers = ""
    
    -- Use array-based dispatch for better obfuscation
    if obfuscate then
        handlers = string.format([[
        local __HANDLERS__ = {
            [0x01] = function() %s(%s[%s + 1]) end,  -- LOADK
            [0x02] = function() %s(nil) end,  -- LOADNIL
            [0x03] = function() %s(%s == 1) end,  -- LOADBOOL
            [0x10] = function() local b=%s() local a=%s() %s(a+b) end,  -- ADD
            [0x11] = function() local b=%s() local a=%s() %s(a-b) end,  -- SUB
            [0x12] = function() local b=%s() local a=%s() %s(a*b) end,  -- MUL
            [0x13] = function() local b=%s() local a=%s() %s(a/b) end,  -- DIV
            [0x14] = function() local b=%s() local a=%s() %s(a%%%%b) end,  -- MOD
            [0x15] = function() local b=%s() local a=%s() %s(a^b) end,  -- POW
            [0x16] = function() %s(-%s()) end,  -- UNM
            [0x20] = function() local b=%s() local a=%s() %s(a==b) end,  -- EQ
            [0x21] = function() local b=%s() local a=%s() %s(a~=b) end,  -- NE
            [0x22] = function() local b=%s() local a=%s() %s(a<b) end,  -- LT
            [0x23] = function() local b=%s() local a=%s() %s(a>b) end,  -- GT
            [0x24] = function() local b=%s() local a=%s() %s(a<=b) end,  -- LE
            [0x25] = function() local b=%s() local a=%s() %s(a>=b) end,  -- GE
            [0x30] = function() %s(not %s()) end,  -- NOT
            [0x40] = function() %s(%s[%s[%s+1]]) end,  -- GETGLOBAL
            [0x41] = function() %s[%s[%s+1]] = %s() end,  -- SETGLOBAL
            [0x42] = function() %s(%s[%s]) end,  -- GETLOCAL
            [0x43] = function() %s[%s] = %s() end,  -- SETLOCAL
            [0x50] = function() %s({}) end,  -- NEWTABLE
            [0x51] = function() local k=%s() local t=%s() %s(t[k]) end,  -- GETTABLE
            [0x52] = function() local v=%s() local k=%s() local t=%s() t[k]=v end,  -- SETTABLE
            [0x61] = function()  -- CALL
                local args={}
                for i=1,%s do table.insert(args,1,%s()) end
                local f=%s()
                local r={f(unpack(args))}
                for _,v in ipairs(r) do %s(v) end
            end,
            [0x62] = function() %s=true end,  -- RETURN
            [0x70] = function() %s=%s+%s end,  -- JMP
            [0x71] = function() if %s() then %s=%s+%s end end,  -- JMPT
            [0x72] = function() if not %s() then %s=%s+%s end end,  -- JMPF
            [0x90] = function() local b=%s() local a=%s() %s(a..b) end,  -- CONCAT
            [0x91] = function() %s(#%s()) end,  -- LEN
            [0xA0] = function() %s() end,  -- DUP
            [0xA1] = function() %s() end,  -- POP
            [0xFF] = function() %s=true end,  -- HALT
        }
        
        local handler = __HANDLERS__[%s]
        if handler then handler() end
]],
            names.push, names.constants, names.operand,
            names.push,
            names.push, names.operand,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.push, names.pop,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.push,
            names.push, names.pop,
            names.push, names.globals, names.constants, names.operand,
            names.globals, names.constants, names.operand, names.pop,
            names.push, names.locals, names.operand,
            names.locals, names.operand, names.pop,
            names.push,
            names.pop, names.pop, names.push,
            names.pop, names.pop, names.pop,
            names.operand, names.pop,
            names.pop,
            names.push,
            names.halted,
            names.pc, names.pc, names.operand,
            names.pop, names.pc, names.pc, names.operand,
            names.pop, names.pc, names.pc, names.operand,
            names.pop, names.pop, names.push,
            names.push, names.pop,
            names.dup,
            names.pop,
            names.halted,
            names.opcode
        )
    else
        -- Readable if-else chain
        handlers = string.format([[
        if %s == 0x01 then  -- LOADK
            %s(%s[%s + 1])
        elseif %s == 0x02 then  -- LOADNIL
            %s(nil)
        elseif %s == 0x03 then  -- LOADBOOL
            %s(%s == 1)
        elseif %s == 0x10 then  -- ADD
            local b = %s()
            local a = %s()
            %s(a + b)
        elseif %s == 0x11 then  -- SUB
            local b = %s()
            local a = %s()
            %s(a - b)
        elseif %s == 0x12 then  -- MUL
            local b = %s()
            local a = %s()
            %s(a * b)
        elseif %s == 0x13 then  -- DIV
            local b = %s()
            local a = %s()
            %s(a / b)
        elseif %s == 0x14 then  -- MOD
            local b = %s()
            local a = %s()
            %s(a %% b)
        elseif %s == 0x15 then  -- POW
            local b = %s()
            local a = %s()
            %s(a ^ b)
        elseif %s == 0x16 then  -- UNM
            %s(-%s())
        elseif %s == 0x20 then  -- EQ
            local b = %s()
            local a = %s()
            %s(a == b)
        elseif %s == 0x30 then  -- NOT
            %s(not %s())
        elseif %s == 0x40 then  -- GETGLOBAL
            %s(%s[%s[%s + 1]])
        elseif %s == 0x41 then  -- SETGLOBAL
            %s[%s[%s + 1]] = %s()
        elseif %s == 0x42 then  -- GETLOCAL
            %s(%s[%s])
        elseif %s == 0x43 then  -- SETLOCAL
            %s[%s] = %s()
        elseif %s == 0x50 then  -- NEWTABLE
            %s({})
        elseif %s == 0x51 then  -- GETTABLE
            local k = %s()
            local t = %s()
            %s(t[k])
        elseif %s == 0x52 then  -- SETTABLE
            local v = %s()
            local k = %s()
            local t = %s()
            t[k] = v
        elseif %s == 0x61 then  -- CALL
            local args = {}
            for i = 1, %s do
                table.insert(args, 1, %s())
            end
            local func = %s()
            local results = {func(unpack(args))}
            for _, result in ipairs(results) do
                %s(result)
            end
        elseif %s == 0x62 then  -- RETURN
            %s = true
        elseif %s == 0x70 then  -- JMP
            %s = %s + %s
        elseif %s == 0x71 then  -- JMPT
            if %s() then
                %s = %s + %s
            end
        elseif %s == 0x72 then  -- JMPF
            if not %s() then
                %s = %s + %s
            end
        elseif %s == 0x90 then  -- CONCAT
            local b = %s()
            local a = %s()
            %s(a .. b)
        elseif %s == 0x91 then  -- LEN
            %s(#%s())
        elseif %s == 0xA0 then  -- DUP
            %s()
        elseif %s == 0xA1 then  -- POP
            %s()
        elseif %s == 0xFF then  -- HALT
            %s = true
        end
]],
            names.opcode, names.push, names.constants, names.operand,
            names.opcode, names.push,
            names.opcode, names.push, names.operand,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.push, names.pop,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.push, names.pop,
            names.opcode, names.push, names.globals, names.constants, names.operand,
            names.opcode, names.globals, names.constants, names.operand, names.pop,
            names.opcode, names.push, names.locals, names.operand,
            names.opcode, names.locals, names.operand, names.pop,
            names.opcode, names.push,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.pop, names.pop, names.pop,
            names.opcode, names.operand, names.pop, names.pop, names.push,
            names.opcode, names.halted,
            names.opcode, names.pc, names.pc, names.operand,
            names.opcode, names.pop, names.pc, names.pc, names.operand,
            names.opcode, names.pop, names.pc, names.pc, names.operand,
            names.opcode, names.pop, names.pop, names.push,
            names.opcode, names.push, names.pop,
            names.opcode, names.dup,
            names.opcode, names.pop,
            names.opcode, names.halted
        )
    end
    
    return handlers
end

-- === Anti-Debugging ===

function VMGenerator:generateAntiDebug(names)
    return string.format([[

-- Anti-debugging checks
local function __CHECK_DEBUG__()
    -- Check for debug library
    if debug and debug.getinfo then
        error("Debugging detected", 0)
    end
    
    -- Check for common debugger functions
    if getfenv or setfenv then
        error("Environment manipulation detected", 0)
    end
    
    -- Timing check
    local start = os.clock()
    for i = 1, 1000 do end
    if os.clock() - start > 0.1 then
        error("Execution timing anomaly", 0)
    end
end

-- Run checks periodically
math.randomseed(os.time())
if math.random(1, 10) > 5 then
    __CHECK_DEBUG__()
end
]])
end

-- === Name Generation ===

function VMGenerator:generateObfuscatedNames()
    return {
        stack = self:randomName(),
        sp = self:randomName(),
        locals = self:randomName(),
        globals = self:randomName(),
        push = self:randomName(),
        pop = self:randomName(),
        peek = self:randomName(),
        dup = self:randomName(),
        bytecode = self:randomName(),
        instructions = self:randomName(),
        constants = self:randomName(),
        encrypted = self:randomName(),
        key = self:randomName(),
        pc = self:randomName(),
        halted = self:randomName(),
        instr = self:randomName(),
        opcode = self:randomName(),
        operand = self:randomName(),
        i = self:randomName(),
        const = self:randomName(),
    }
end

function VMGenerator:generateNormalNames()
    return {
        stack = "stack",
        sp = "sp",
        locals = "locals",
        globals = "globals",
        push = "push",
        pop = "pop",
        peek = "peek",
        dup = "dup",
        bytecode = "bytecode",
        instructions = "instructions",
        constants = "constants",
        encrypted = "encrypted",
        key = "key",
        pc = "pc",
        halted = "halted",
        instr = "instr",
        opcode = "opcode",
        operand = "operand",
        i = "i",
        const = "const",
    }
end

function VMGenerator:randomName()
    local chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    local name = "_"
    for i = 1, math.random(6, 10) do
        local idx = math.random(1, #chars)
        name = name .. chars:sub(idx, idx)
    end
    return name
end

-- === Final Obfuscation ===

function VMGenerator:finalObfuscation(code)
    -- Add junk code
    local junk = [[
-- Integrity verification
local __VERIFY__ = function(x) return x end
local __INIT__ = os.time()
]]
    
    return junk .. "\n" .. code
end

return VMGenerator